### ISSUE TITLE
Stops updating data

### ISSUE THREAD

**Issue by pvpowered** [suaveolent/ha-hoymiles-wifi#31] opened 2024-04-24 08:26 UTC
**Describe the bug**
After working for a short time (minutes to hours), the update of all power data stops. A restart of Home Assistant fixes the issue.

Tested with DTU Wlite S in combination with HM-300.

**To Reproduce**
1. Setup Home Assistant Integration.
2. Wait...

**Expected behavior**
Keep updating data.

**System (please complete the following information):**
 - Raspberry Pi 4
 - OS: Home Assistant 12.2

**Additional context**
I found the following text every 15 min in the debug log:
"DEBUG (MainThread) [custom_components.hoymiles_wifi.sensor] Returning last known value instead of 0.0 for AC-Tagesenergie to avoid resetting total_increasing counter"

Anyways, I would like to thank you for the time and effort you have invested in developing this tool!

**Comment by suaveolent** [comment] 2024-04-24 08:38
Thanks, the error indicates that the DTU is not responding. 
Now we need to figure out why. 

Are you running the latest firmware on the DTU? 
Are you using any other components which might access the DTU? 
Are you using something else at the same time, e.g. OpenDTU?

**Comment by pvpowered** [comment] 2024-04-24 15:26
To the best of my knowledge, my firmware version is up to date.
The only other component is S-Miles Cloud and the mobile application. But this should not affect the Home Assistant integration. There is no second DTU like OpenDTU or AhoyDTU running. 
I tried to run this [Addon](https://github.com/banny310/hoymiles-dtu-homeassistant-addon) before. However, it did not work at all (no connection to DTU) and I removed this addon before starting to use your integration. I was very happy to see data using your integration.
However, today the communication between Home Assistant and DTU works exactly once after reboot. The received data keeps being frozen until the next reboot.


DTU:
Hardware version H06.01.01 
Software version V00.03.12

Inverter:
Hardware version H00.08.00
Software version V01.00.14

**Comment by suaveolent** [comment] 2024-04-25 11:08
I'm wondering if this is related to https://github.com/suaveolent/ha-hoymiles-wifi/issues/32#issuecomment-2075150671 and this being an issue on Hoymiles side?

**Comment by pvpowered** [comment] 2024-04-25 11:52
After reinstallation of the integration, i increased the update interval to 60 s. It appears to work fine for the last 18 hours with one minor flaw: there is loss of data at random times (cf. screenshot of voltage). This issue applies to all data.

<img width="1128" alt="Voltage" src="https://github.com/suaveolent/ha-hoymiles-wifi/assets/167202833/3d1dec55-3bea-446a-a7c0-a86b633d7ed3">

Here is an exemplary log with issue at 19:47:30:
2024-04-24 19:46:23.504 DEBUG (MainThread) [custom_components.hoymiles_wifi.coordinator] Hoymiles data coordinator update
2024-04-24 19:46:25.891 DEBUG (MainThread) [custom_components.hoymiles_wifi.coordinator] Finished fetching hoymiles_wifi data in 2.387 seconds (success: True)
2024-04-24 19:46:25.892 DEBUG (MainThread) [custom_components.hoymiles_wifi.sensor] Returning last known value instead of 0.0 for AC-Tagesenergie to avoid resetting total_increasing counter
2024-04-24 19:47:25.505 DEBUG (MainThread) [custom_components.hoymiles_wifi.coordinator] Hoymiles data coordinator update
2024-04-24 19:47:30.517 DEBUG (MainThread) [custom_components.hoymiles_wifi.coordinator] Unable to retrieve real data new. Inverter might be offline.
2024-04-24 19:47:30.518 DEBUG (MainThread) [custom_components.hoymiles_wifi.coordinator] Finished fetching hoymiles_wifi data in 5.013 seconds (success: True)
2024-04-24 19:47:30.518 DEBUG (MainThread) [custom_components.hoymiles_wifi.sensor] Returning last known value instead of 0.0 for AC-Tagesenergie to avoid resetting total_increasing counter
2024-04-24 19:47:30.520 DEBUG (MainThread) [custom_components.hoymiles_wifi.sensor] Returning last known value instead of 0.0 for Port 1 DC-Gesamtenergie to avoid resetting total_increasing counter
2024-04-24 19:47:30.521 DEBUG (MainThread) [custom_components.hoymiles_wifi.sensor] Returning last known value instead of 0.0 for Port 1 DC-Tagesenergie to avoid resetting total_increasing counter
2024-04-24 19:48:30.505 DEBUG (MainThread) [custom_components.hoymiles_wifi.coordinator] Hoymiles data coordinator update
2024-04-24 19:48:32.346 DEBUG (MainThread) [custom_components.hoymiles_wifi.coordinator] Finished fetching hoymiles_wifi data in 1.841 seconds (success: True)
2024-04-24 19:48:32.347 DEBUG (MainThread) [custom_components.hoymiles_wifi.sensor] Returning last known value instead of 0.0 for AC-Tagesenergie to avoid resetting total_increasing counter

**Comment by pvpowered** [comment] 2024-04-25 11:54
> I'm wondering if this is related to #32 and this being an issue on Hoymiles side?

I don't think so. Daily energy keeps increasing.

**Comment by suaveolent** [comment] 2024-04-26 09:23
> After reinstallation of the integration, i increased the update interval to 60 s. It appears to work fine for the last 18 hours with one minor flaw: there is loss of data at random times (cf. screenshot of voltage). This issue applies to all data.

Thanks, It might be that the DTU is overwhelmed by the short default update interval.
The graph you posted reminds me of https://github.com/suaveolent/ha-hoymiles-wifi/issues/14.

It could be that there are some overlaps of the cycles of the integrations commands which causes the DTU to be overwhelmed. Although interestingly this does not happen to the HMS-800W-2T any more.

**Comment by blazx6** [comment] 2024-05-06 05:48
> > After reinstallation of the integration, i increased the update interval to 60 s. It appears to work fine for the last 18 hours with one minor flaw: there is loss of data at random times (cf. screenshot of voltage). This issue applies to all data.
> 
> Thanks, It might be that the DTU is overwhelmed by the short default update interval. The graph you posted reminds me of #14.
> 
> It could be that there are some overlaps of the cycles of the integrations commands which causes the DTU to be overwhelmed. Although interestingly this does not happen to the HMS-800W-2T any more.

I have a new installation with HMS-800W-2T and the updates worked fine for a day but now the values are not refreshed anymore in HA. Over the S-Miles App the Data is updated normally. HMS is o nthe latest available FW, HA was uodated to the latest Version yesterday. Restart of the HA does not help.

HA working in Hyper-V on Windows 11.

**Comment by suaveolent** [comment] 2024-05-08 09:02
> > > After reinstallation of the integration, i increased the update interval to 60 s. It appears to work fine for the last 18 hours with one minor flaw: there is loss of data at random times (cf. screenshot of voltage). This issue applies to all data.
> > 
> > 
> > Thanks, It might be that the DTU is overwhelmed by the short default update interval. The graph you posted reminds me of #14.
> > It could be that there are some overlaps of the cycles of the integrations commands which causes the DTU to be overwhelmed. Although interestingly this does not happen to the HMS-800W-2T any more.
> 
> I have a new installation with HMS-800W-2T and the updates worked fine for a day but now the values are not refreshed anymore in HA. Over the S-Miles App the Data is updated normally. HMS is on the latest available FW, HA was updated to the latest Version yesterday. Restart of the HA does not help.
> 
> HA working in Hyper-V on Windows 11.

Are you running your inverter together with a battery? Have you tried restarting the DTU ?

**Comment by blazx6** [comment] 2024-05-08 09:19
Hi,

No, no battery, just the inverter plugged in directly to the grid.

DTU turns off every night when there is no solar energy produced, I didn't
perform a factory reset of the DTU.

Kind regards

V sre., 8. maj 2024, 11:03 je oseba suaveolent ***@***.***>
napisala:

**Comment by suaveolent** [comment] 2024-05-08 09:20
Could it be, that the IP-Adress you are using has changed since the install (Some routers will not assign the same ip after the device reconnects)

**Comment by blazx6** [comment] 2024-05-08 09:27
Shouldn't be the cause because I have defined a fixed IP address for the
DTU in the Router DHCP settings but I can double check that.

V sre., 8. maj 2024, 11:21 je oseba suaveolent ***@***.***>
napisala:

**Comment by suaveolent** [comment] 2024-05-08 15:16
Can you also verify if you can ping the inverter from your home assistance instance?

**Comment by blazx6** [comment] 2024-05-09 05:52
I had the option to check the network settings today and you were right.
From some reason the Router didn't assign the designated IP to the DTU. I
deleted the DHCP config for the DTU and created a new one, restarted the
Router and am now able to see the DTU data in HA again. Thanks for the idea!

V sre., 8. maj 2024, 17:17 je oseba suaveolent ***@***.***>
napisala:

**Comment by suaveolent** [comment] 2024-05-09 07:10
Great, 
Glad it works! 
Closing the issue then.

**Closed by suaveolent** 2024-05-09 07:10 UTC
